spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_chat?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: ${mysql_pwd}
    driver-class-name: com.mysql.cj.jdbc.Driver